@baseUrl=http://localhost:3001/authors

GET {{baseUrl}}

###
GET {{baseUrl}}/66acc62e229d23f0a20f8a47

###
POST {{baseUrl}}
Content-Type: application/json

{
    "name": "gente13",
    "surname": "acaso11",
    "email": "mail13@gmail.com",
    "birthDate": "2024-01-01",
    "avatar": "none"
}

###
PUT {{baseUrl}}/66c86bf5bd9de5028233e069
Content-Type: application/json

{
    "name": "gnappoboh",
    "surname": "boh",
    "email": "p.bo2h@gmail.com",
    "birthDate": "2024-01-01",
    "avatar": "none"
}

###
DELETE {{baseUrl}}/66c86bf5bd9de5028233e069

###
GET {{baseUrl}}/66acc62e229d23f0a20f8a47/blogPosts