@baseUrl=http://localhost:3001/authors

GET {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ0Njg2ZGFlMDNkZTRjZjYyMjFkZmEiLCJpYXQiOjE3MjU2NDIwMzEsImV4cCI6MTcyNTY0NTYzMX0.ve09lot6oFhnSCsSBitRoPt-VJNUwQQTtwHVKzvoaXA

###
GET {{baseUrl}}/66acc62e229d23f0a20f8a47
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ4YTA5YmE2ZTMzMWNhN2ZmZmM0ZWMiLCJpYXQiOjE3MjU3MTU1NzAsImV4cCI6MTcyNTcxOTE3MH0.QC_mZBiL7RuicFKNQ5H4M25uF_R_caNPahk2leNV_E8

###
POST {{baseUrl}}
Content-Type: application/json

{
    "name": "gente14",
    "surname": "acaso14",
    "email": "mail14@gmail.com",
    "password": "password123",
    "birthDate": "2024-01-01",
    "avatar": "none"
}

###
PUT {{baseUrl}}/66c86bf5bd9de5028233e069
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ0Njg2ZGFlMDNkZTRjZjYyMjFkZmEiLCJpYXQiOjE3MjUyMDc2NTEsImV4cCI6MTcyNTIxMTI1MX0.HHCBRV0R3Jo7M5YebQD9m7_brt17qCHvzolW8lBEdOE

{
    "name": "gnappoboh",
    "surname": "boh",
    "email": "p.bo2h@gmail.com",
    "birthDate": "2024-01-01",
    "avatar": "none"
}

###
DELETE {{baseUrl}}/66c86bf5bd9de5028233e069
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ0Njg2ZGFlMDNkZTRjZjYyMjFkZmEiLCJpYXQiOjE3MjUyMDc2NTEsImV4cCI6MTcyNTIxMTI1MX0.HHCBRV0R3Jo7M5YebQD9m7_brt17qCHvzolW8lBEdOE

###
GET {{baseUrl}}/66acc62e229d23f0a20f8a47/blogPosts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ0Njg2ZGFlMDNkZTRjZjYyMjFkZmEiLCJpYXQiOjE3MjUyMDc2NTEsImV4cCI6MTcyNTIxMTI1MX0.HHCBRV0R3Jo7M5YebQD9m7_brt17qCHvzolW8lBEdOE