@baseUrl=http://localhost:3001/auth

POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "mail14@gmail.com",
    "password": "password123"
}

###
GET {{baseUrl}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ0Njg2ZGFlMDNkZTRjZjYyMjFkZmEiLCJpYXQiOjE3MjU2NDIwMzEsImV4cCI6MTcyNTY0NTYzMX0.ve09lot6oFhnSCsSBitRoPt-VJNUwQQTtwHVKzvoaXA
Content-Type: application/json

###
GET {{baseUrl}}/login-google