@baseUrl=http://localhost:3001/blogPosts

GET {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ4YTA5YmE2ZTMzMWNhN2ZmZmM0ZWMiLCJpYXQiOjE3MjU3MTU1NzAsImV4cCI6MTcyNTcxOTE3MH0.QC_mZBiL7RuicFKNQ5H4M25uF_R_caNPahk2leNV_E8

###
GET {{baseUrl}}/66af55f03281da3acf942353
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ4YTA5YmE2ZTMzMWNhN2ZmZmM0ZWMiLCJpYXQiOjE3MjU3MTU1NzAsImV4cCI6MTcyNTcxOTE3MH0.QC_mZBiL7RuicFKNQ5H4M25uF_R_caNPahk2leNV_E8

###
POST {{baseUrl}}
Content-Type: application/json

{
    "category": "Sport",
    "title": "Articolo 12 creato da un altro tizio",
    "cover": "urlCover" ,
    "readTime": {
        "value": 10,
        "unit": "min"
    },
    "authorId": "66ad2727c5b6282c3722d3a3",
    "content": "Articolo 12 molto lungo ciao."
}

###
PUT {{baseUrl}}/66af552abf036eedfb8c1e1b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ0Njg2ZGFlMDNkZTRjZjYyMjFkZmEiLCJpYXQiOjE3MjUyMDc2NTEsImV4cCI6MTcyNTIxMTI1MX0.HHCBRV0R3Jo7M5YebQD9m7_brt17qCHvzolW8lBEdOE

{
    "category": "Sport",
    "title": "POst modificato",
    "cover": "urlCover" ,
    "readTime": {
        "value": 10,
        "unit": "min"
    },
    "authorId": "66acc62e229d23f0a20f8a47",
    "content": "Testo modificato 2."
}

###
DELETE {{baseUrl}}/66af5567bf036eedfb8c1e25